name: CI

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Lint & Typecheck
        run: |
          ruff check src tests
          black --check src tests
          mypy src

      - name: Test
        run: pytest -q --cov=src --cov-report=xml

      - name: Evaluation
        run: python -m notebook_refactor_agent.eval.run eval/suite.yaml

      - name: Upload eval summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eval-summary-${{ matrix.python-version }}
          path: |
            eval_runs/**/summary.json
            eval_runs/**/summary.csv